apiVersion: apps/v1
kind: Deployment
metadata:
  name: better-assistant-fe-deployment
  labels:
    app: better-assistant-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: better-assistant-fe
  template:
    metadata:
      labels:
        app: better-assistant-fe
    spec:
      containers:
      - name: better-assistant-fe
        image: ${DOCKER_REGISTRY_URL}/better-assistant-fe:${TAG_NAME}
        imagePullPolicy: Always # 이미지 여부 상관없이 일단 다운로드 진행
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: better-assistant-fe-cm
        livenessProbe: # health_check용 session page 첨부 필수
          httpGet:
            path: /api/health
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 5 #파드 정상 투입까지 대기시간
          periodSeconds: 3
          timeoutSeconds: 5
        readinessProbe: # health_check용 session page 첨부 필수
          httpGet:
            path: /api/health
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 5 #파드 정상 투입까지 대기시간
          periodSeconds: 3
          timeoutSeconds: 10
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: better-assistant-fe-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
spec:
  type: NodePort
  selector:
    app: better-assistant-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000