import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Button } from "@/components/ui/button"
import { User } from "lucide-react"
import Link from 'next/link';

import SideBar from "@/components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Better Assistant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col h-screen bg-background">
          <header className="flex items-center justify-between p-4 border-b bg-muted">
            <h1 className="text-2xl font-bold">
              <Link href="/">
                <h1>Better Assistant</h1>
              </Link>
            </h1>

            <Button variant="ghost" size="icon" aria-label="User profile" >
              <User className="h-5 w-5" />
            </Button>
          </header>

          <div className="flex flex-1 overflow-hidden">
            {/* Main Content */}
            {children}

            {/* Side Bar */}
            <SideBar />

          </div>

          {/* Footer */}
          <footer className="p-4 border-t bg-muted text-center">
            <p className="text-sm text-muted-foreground">© 2025 SIHA All rights reserved.</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
