name: CI/CD Pipeline

on:
  release:
    types: [published]
  push:
    branches:
      - main
      - develop

jobs:
  docker:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3      
      
      - name: Log in to Private Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image to Private Docker Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: |
            NEXT_PUBLIC_SERVER_ENDPOINT=${{ secrets.NEXT_PUBLIC_SERVER_ENDPOINT }}
          tags: ${{ secrets.DOCKER_REGISTRY_URL }}/better-assistant-fe:${{ github.event.release.tag_name }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Kubeconfig
        run: |
          mkdir ~/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" > ~/.kube/config

      - name: Download NCP IAM Authenticator
        run: |
          curl -o ncp-iam-authenticator -L https://github.com/NaverCloudPlatform/ncp-iam-authenticator/releases/latest/download/ncp-iam-authenticator_linux_amd64
          chmod +x ./ncp-iam-authenticator
          mv ncp-iam-authenticator /usr/local/bin/ncp-iam-authenticator

      - name: Configure Kubernetes with NCP IAM
        run: |
          export PATH=$PATH:/usr/local/bin

      - name: Replace Docker Registry URL and Tag Name
        run: |
          sed -i 's/\${TAG_NAME}/'"${{ github.event.release.tag_name }}"'/g' better-assistant-fe.yaml
          sed -i 's/\${DOCKER_REGISTRY_URL}/'"${{ secrets.DOCKER_REGISTRY_URL }}"'/g' better-assistant-fe.yaml
        
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f better-assistant-fe.yaml
        env:
          NCLOUD_ACCESS_KEY: ${{ secrets.NCLOUD_ACCESS_KEY }}
          NCLOUD_SECRET_KEY: ${{ secrets.NCLOUD_SECRET_KEY }}
          NCLOUD_API_GW: https://ncloud.apigw.ntruss.com
